# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["WWCUSERNAME"] %>
  password: <%= ENV["WWCPASSWORD"] %>

development:
  <<: *default
  database: white_word_cells_backend_development
  
test:
  <<: *default
  database: white_word_cells_backend_test

production:
  <<: *default
  database: white_word_cells_backend_production
  username: <%= ENV["WWCUSERNAME"] %>
  password: <%= ENV["WCCPASSWORD"] %>
